### ISSUE TITLE
`generateHtmlResponse` doesn't support async overrides

### ISSUE THREAD

**Issue by liangchunn** [crookse/deno-drash#48]
### Description
In [Part 2 of the Tutorial](https://crookse.github.io/deno-drash/#/tutorials/creating-an-app-hello-world-part-2), an override of `Drash.Http.Response` is introduced with member method of `async generateHtmlResponse()`. 

```ts
class Response extends Drash.Http.Response {
  public async generateHtmlResponse(): Promise<any> {
    const path = Deno.cwd() + "/src/index.ejs"
    const rawOutput = await renderFile(path, {body: this.body});
    const html = rawOutput.toString();
    return html;
  }
}

Drash.Http.Response = Response;
```

The problem arises when `Drash.Http.Response.send()` calls `Drash.Http.Response.generateResponse()` which invokes the overriden function `Response.generateHtmlResponse()` _without_ `await`ing it:

```ts
// deno-drash/http/response.ts
public send(): any {
  let body = this.generateResponse(); // <--- returns a promise, should be awaited
  let output = {
    status: this.status_code,
    headers: this.headers,
    body: new TextEncoder().encode(body) // <-- ERR! trying to encode `Promise {}`
  };

  this.request.respond(output);

  return output;
}
```

Which causes it to crash:
```
Deno server started at localhost:1337.

Request received: GET /
Calling HomeResource.GET() method.
Sending response. Content-Type: text/html. Status: 200 (OK).
Error occurred while handling request: GET /
Sending response. Content-Type: text/html. Status: 500 (Internal Server Error).
Uncaught TypeError: input is not iterable
    at stringToCodePoints (js/text_encoding.ts:51:19)
    at encode (js/text_encoding.ts:456:36)
    at send (file:///Users/lwong/Library/Caches/deno/deps/https/raw.githubusercontent.com/crookse/deno-drash/v0.7.8/src/http/response.ts:184:31)
    at handleHttpRequestError (file:///Users/lwong/Library/Caches/deno/deps/https/raw.githubusercontent.com/crookse/deno-drash/v0.7.8/src/http/server.ts:281:21)
    at handleHttpRequest (file:///Users/lwong/Library/Caches/deno/deps/https/raw.githubusercontent.com/crookse/deno-drash/v0.7.8/src/http/server.ts:207:21)
    at run (file:///Users/lwong/Library/Caches/deno/deps/https/raw.githubusercontent.com/crookse/deno-drash/v0.7.8/src/http/server.ts:330:12)
```

### Reproduction steps
Follow the tutorial with the `deno@0.3.7` and `drash@0.7.8`

### Expected behaviour
Overriding `generateHtmlResponse` with an `async` function should work

### Package versions

| package | version |
|---------|--------|
| `deno` | 0.3.7 |
| `deno-drash` | 0.7.8 |
| `dejs` | 0.2.0 |

**Comment by crookse** [comment]
Fix is in place: `import Drash from "https://deno.land/x/drash@v0.7.9/mod.ts";`

Thanks for catching that @liangchunn !

**Comment by crookse** [comment]
Feel free to send a pull request next time @liangchunn
